main/urls.py
from django.urls import path

from main import views

app_name = 'main'
urlpatterns = [
    path('', views.home, name='home'),
    path('add_todo', views.add_todo, name='add_todo'),
    path('delete_todo/<int:todo_id>', views.delete_todo, name='delete_todo'),
]

todoapp/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
]

main/models.py
from django.db import models

# Create your models here.
class Todo(models.Model):
    added_date = models.DateTimeField()
    text = models.CharField(max_length=200)

main/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.utils import timezone
from django.views.decorators.csrf import csrf_exempt

from main.models import Todo

# Create your views here.


def home(request):
    todo_items = Todo.objects.order_by('added_date').all()

    return render(request, 'main/index.html', {'todo_items': todo_items})


@csrf_exempt
def add_todo(request):
    current_date = timezone.now()
    content = request.POST.get('content')

    Todo.objects.create(added_date=current_date, text=content)

    return HttpResponseRedirect(reverse('main:home'))


@csrf_exempt
def delete_todo(request, todo_id):
    Todo.objects.get(pk=todo_id).delete()

    return HttpResponseRedirect(reverse('main:home'))

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>To Do App</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <nav class="navbar navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="{% url 'main:home' %}">To Do App</a>
        </div>
    </nav>

    {% block content %}

    {% endblock content %}
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

templates/main/index.html
{% extends 'base.html' %}

{% block content %}
    <div class="container mt-4">
        <div class="row">
            <div class="col">
                <h2>Add item</h2>
                <form class="form-inline" action="{% url 'main:add_todo' %}" method="post">
                    <input class="form-control mb-2 mb-sm-0 mr-sm-2" type="text" name="content" placeholder="Type here..." aria-describedby="typetodo">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
        <div class="row mt-4">
            <ul class="list-group">
                {% for todo_item in todo_items %}
                    <li class="list-group-item d-flex align-items-center">
                        <p class="m-0">{{ todo_item.text }}</p>
                        <div class="float-right">
                            <form action="{% url 'main:delete_todo' todo_item.id %}" method="post">
                                <button type="submit" class="btn btn-danger ml-3">Delete</button>
                            </form>
                        </div>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock content %}